name: Deb
on:
  push:
    branches: [main]
  workflow_dispatch:
  workflow_call:
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      THEOS: ${{ github.workspace }}/.theos
      CI: true
    steps:
      - uses: actions/checkout@v7
      - name: Setup
        run: bash -c "$(curl -fsSL https://raw.githubusercontent.com/theos/theos/master/bin/install-theos)"
      - name: Test
        run: python3 -m unittest discover -s Tests -v
      - name: Build
        run: make clean package FINALPACKAGE=1
      - uses: actions/upload-artifact@v7
        with:
          name: YTKACE-deb
          path: packages/*.deb
          if-no-files-found: error

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v8
        with:
          name: YTKACE-deb
          path: packages

      - name: Publish release
        uses: softprops/action-gh-release@v3
        with:
          draft: false
          tag_name: deb-${{ github.run_number }}
          name: Deb ${{ github.run_number }}
          files: packages/*.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
